"""
RaTlsCert — Self-signed TLS certificate with embedded TeeQuote.

RA-TLS design
-------------
Remote Attestation TLS (RA-TLS) embeds a TEE attestation quote directly in
the TLS certificate, so the TLS handshake IS the attestation:

1. Miner generates an ephemeral ECDSA P-256 key pair.
2. Miner generates a TeeQuote bound to (peer_id, epoch).
   The quote's report_data = sha256(peer_id:epoch) — identity binding.
3. Miner creates a self-signed X.509 cert:
   - Subject: CN=<peer_id[:16]>
   - Not Before: now, Not After: now + 24 hours
   - Custom extension OID 1.3.6.1.4.1.99999.1 (TEE_QUOTE_OID):
     DER-encoded TeeQuote JSON bytes
4. Cert is served as the TLS server certificate.
5. Validator (RA-TLS client):
   - Connects with TLS (no CA verification — cert is self-signed by design)
   - Extracts the TEE_QUOTE_OID extension value
   - Deserialises → TeeQuote
   - Runs DcapVerifier.verify(peer_id, epoch) against the embedded quote
   - If ok → session proceeds; if not ok → drops connection

Security properties
-------------------
- Freshness: cert valid for 24h; validator checks quote.nonce == current_epoch
- Identity: report_data = sha256(peer_id:epoch); validator checks peer_id
- Non-repudiation: cert key pair is ephemeral, renewed each epoch
- No CA trust: self-signed is intentional — trust derives from hardware, not PKI

Mock path
---------
MockBackend generates an HMAC-signed quote. Validator verifies the HMAC.
This is the development/CI path. Set MOCK_TEE=true (default).

Real path (TDX/SEV-SNP)
-----------------------
TdxBackend / SevSnpBackend generates a DCAP quote. The cert's public key hash
is embedded in the quote's report_data alongside peer_id:epoch (future M002
enhancement). Full DCAP chain verification runs in the validator.

OID
---
TEE_QUOTE_OID = 1.3.6.1.4.1.99999.1  (enterprise OID space, placeholder)
For production deployment, register a proper OID under your arc.
"""

from __future__ import annotations

import datetime
import json
from dataclasses import dataclass

from cryptography import x509
from cryptography.hazmat.primitives import hashes, serialization
from cryptography.hazmat.primitives.asymmetric import ec
from cryptography.x509.oid import NameOID

from subnet.tee.quote import TeeQuote

# Custom OID for the TeeQuote extension
# 1.3.6.1.4.1.99999.1 — enterprise arc, placeholder for production
TEE_QUOTE_OID = x509.ObjectIdentifier("1.3.6.1.4.1.99999.1")

# Cert validity period (one epoch window is sufficient; validators check freshness via nonce)
CERT_VALIDITY_HOURS = 24


@dataclass
class RaTlsCertBundle:
    """
    RA-TLS certificate bundle: cert + private key + embedded quote.

    Fields
    ------
    cert_pem    : PEM-encoded X.509 certificate (served to validators)
    key_pem     : PEM-encoded ECDSA P-256 private key (kept by miner)
    quote       : TeeQuote embedded in the certificate extension
    """

    cert_pem: bytes   # PEM — the RA-TLS cert
    key_pem: bytes    # PEM — ephemeral private key (never leaves enclave)
    quote: TeeQuote   # the embedded quote (for diagnostics)


def generate_ratls_cert(quote: TeeQuote, private_key=None) -> RaTlsCertBundle:
    """
    Generate a self-signed X.509 certificate with a TeeQuote embedded in a custom extension.

    Parameters
    ----------
    quote       : TeeQuote generated by the miner's backend for the current epoch
    private_key : optional ECDSA P-256 private key; if None, a fresh key is generated.
                  When provided, the caller is responsible for ensuring the key's
                  public hash was already bound into the quote's report_data (F-02).

    Returns
    -------
    RaTlsCertBundle with PEM cert, PEM private key, and the embedded quote.
    """
    # Generate ephemeral ECDSA P-256 key pair (or use the one provided)
    if private_key is None:
        private_key = ec.generate_private_key(ec.SECP256R1())

    # Build subject: CN = first 16 chars of peer_id (human-readable, not security-relevant)
    subject = x509.Name([
        x509.NameAttribute(NameOID.COMMON_NAME, f"ratls-{quote.peer_id[:16]}"),
        x509.NameAttribute(NameOID.ORGANIZATION_NAME, "Hypertensor-TEE"),
    ])

    # Validity: now → now + 24h
    now = datetime.datetime.now(datetime.timezone.utc)
    not_after = now + datetime.timedelta(hours=CERT_VALIDITY_HOURS)

    # Encode the TeeQuote as the extension value
    # We use a DER OctetString wrapping the JSON bytes
    quote_json_bytes = quote.to_bytes()

    # Build the X.509 extension: OID + critical=False + DER-encoded value
    # cryptography library wraps the raw bytes in a DER OctetString automatically
    # when we use UnrecognizedExtension
    quote_extension = x509.extensions.Extension(
        oid=TEE_QUOTE_OID,
        critical=False,
        value=x509.UnrecognizedExtension(TEE_QUOTE_OID, quote_json_bytes),
    )

    cert = (
        x509.CertificateBuilder()
        .subject_name(subject)
        .issuer_name(subject)  # self-signed → issuer = subject
        .public_key(private_key.public_key())
        .serial_number(x509.random_serial_number())
        .not_valid_before(now)
        .not_valid_after(not_after)
        .add_extension(
            x509.SubjectAlternativeName([
                x509.DNSName(f"ratls-{quote.peer_id[:32]}"),
            ]),
            critical=False,
        )
        .add_extension(
            x509.BasicConstraints(ca=False, path_length=None),
            critical=True,
        )
        .add_extension(
            x509.UnrecognizedExtension(TEE_QUOTE_OID, quote_json_bytes),
            critical=False,
        )
        .sign(private_key, hashes.SHA256())
    )

    cert_pem = cert.public_bytes(serialization.Encoding.PEM)
    key_pem = private_key.private_bytes(
        encoding=serialization.Encoding.PEM,
        format=serialization.PrivateFormat.TraditionalOpenSSL,
        encryption_algorithm=serialization.NoEncryption(),
    )

    return RaTlsCertBundle(cert_pem=cert_pem, key_pem=key_pem, quote=quote)


def extract_quote_from_cert(cert_pem: bytes) -> TeeQuote:
    """
    Extract and deserialise the TeeQuote from an RA-TLS X.509 certificate.

    Parameters
    ----------
    cert_pem : PEM-encoded X.509 certificate from the miner

    Returns
    -------
    TeeQuote extracted from the TEE_QUOTE_OID extension

    Raises
    ------
    RaTlsExtensionMissingError : if the TEE_QUOTE_OID extension is not present
    RaTlsExtensionParseError   : if the extension value cannot be deserialised
    """
    cert = x509.load_pem_x509_certificate(cert_pem)

    try:
        ext = cert.extensions.get_extension_for_oid(TEE_QUOTE_OID)
    except x509.ExtensionNotFound:
        raise RaTlsExtensionMissingError(
            f"Certificate does not contain TEE_QUOTE_OID extension ({TEE_QUOTE_OID.dotted_string})"
        )

    raw_value = ext.value.value  # UnrecognizedExtension.value = raw bytes
    try:
        return TeeQuote.from_bytes(raw_value)
    except Exception as exc:
        raise RaTlsExtensionParseError(
            f"Failed to deserialise TeeQuote from extension: {exc}"
        ) from exc


def get_cert_public_key_bytes(cert_pem: bytes) -> bytes:
    """
    Extract the raw DER-encoded public key bytes from the cert.
    Used for session key derivation (bind session to the cert key).
    """
    cert = x509.load_pem_x509_certificate(cert_pem)
    return cert.public_key().public_bytes(
        encoding=serialization.Encoding.DER,
        format=serialization.PublicFormat.SubjectPublicKeyInfo,
    )


class RaTlsExtensionMissingError(ValueError):
    """Cert does not contain the TEE_QUOTE_OID extension."""


class RaTlsExtensionParseError(ValueError):
    """TEE_QUOTE_OID extension value could not be deserialised."""
